export type Category =
  | "Regular Flavors"
  | "Seasonal Flavors"
  | "Premium Flavors"
  | "Specialities"
  | "Milkshakes"
  | "Deals";

export interface SizeOption {
  label: string;
  price: number;
}

export interface Product {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  price: number;
  currency: "Rs" | "$";
  category: Category;
  tag?: "Bestseller" | "Heritage" | "Specialty";
  image: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  sizes: SizeOption[];
}

export const products: Product[] = [
  {
    slug: "peshawari",
    name: "Peshawari",
    tagline: "The 1948 Original",
    description: "The very first flavour we ever made - dense, creamy and pure. A legacy of taste in every scoop.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    tag: "Heritage",
    image: "/images/peshawari.webp",
    rating: 4.8,
    reviews: 1200,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "caramel-crunch",
    name: "Caramel Crunch",
    tagline: "Buttery Caramel & Crunch",
    description: "Slow-cooked caramel swirled with a buttery crunch in a rich cream base.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    tag: "Bestseller",
    image: "/images/caramel-crunch.webp",
    rating: 4.8,
    reviews: 1237,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "pista",
    name: "Pista",
    tagline: "Roasted Iranian Pistachios",
    description: "Heavily loaded with premium roasted pistachios for an earthy, nutty crunch.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    tag: "Bestseller",
    image: "/images/pista.webp",
    rating: 4.8,
    reviews: 1274,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "pineapple",
    name: "Pineapple",
    tagline: "Tropical & Tangy",
    description: "Sun-ripened pineapple blended into a smooth, refreshing cream.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/pineapple.webp",
    rating: 4.8,
    reviews: 1311,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "strawberry-cheesecake",
    name: "Strawberry Cheesecake",
    tagline: "Strawberry & Cheesecake",
    description: "Indulge with soft creamy texture ice cream with strawberry & cheesecake mixed in every bite of this most loved flavor.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/strawberry-cheesecake.webp",
    rating: 4.8,
    reviews: 1348,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "cadbury",
    name: "Cadbury",
    tagline: "Classic Chocolate",
    description: "Rich Cadbury chocolate folded into our signature cream base.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/cadbury.webp",
    rating: 4.8,
    reviews: 1385,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "chocolate-chip",
    name: "Chocolate Chip",
    tagline: "Chocolate Chips in Cream",
    description: "Silky cream studded with crunchy chocolate chips.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    tag: "Bestseller",
    image: "/images/chocolate-chip.webp",
    rating: 4.8,
    reviews: 1422,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "kulfa-almond",
    name: "Kulfa Almond",
    tagline: "Roasted Almond Kulfa",
    description: "Roasted almond kulfi, slow-churned to a dense, nutty perfection.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/kulfa-almond.webp",
    rating: 4.8,
    reviews: 1459,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "injeer",
    name: "Injeer",
    tagline: "Fig Infusion",
    description: "Sweet dried figs blended into a smooth, honeyed cream.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/injeer.jpg",
    rating: 4.8,
    reviews: 1496,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "tutti-frutti",
    name: "Tutti Frutti",
    tagline: "Candied Fruit & Cream",
    description: "A burst of colourful candied fruits in a soft vanilla cream.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/tutti-frutti.jpg",
    rating: 4.8,
    reviews: 1533,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "rose-jelly",
    name: "Rose Jelly",
    tagline: "Rose & Jelly",
    description: "Fragrant rose with wobbly rose jelly in a silky base.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/rose-jelly.webp",
    rating: 4.8,
    reviews: 1570,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "kaju",
    name: "Kaju",
    tagline: "Cashew Cream",
    description: "Finely ground cashews folded into a rich, nutty cream.",
    price: 380,
    currency: "Rs",
    category: "Regular Flavors",
    image: "/images/kaju.jpg",
    rating: 4.8,
    reviews: 1607,
    inStock: true,
    sizes: [{ label: "Cup", price: 380 }, { label: "Half Bucket", price: 850 }, { label: "Full Bucket", price: 1700 }, { label: "Family Bucket", price: 5500 }],
  },
  {
    slug: "mango",
    name: "Mango",
    tagline: "Seasonal King of Fruits",
    description: "Made with the finest seasonal mangoes, sweet and intensely fruity.",
    price: 400,
    currency: "Rs",
    category: "Seasonal Flavors",
    tag: "Bestseller",
    image: "/images/mango.webp",
    rating: 4.8,
    reviews: 1644,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "shareefa",
    name: "Shareefa",
    tagline: "Custard Apple Cream",
    description: "The soft, honeyed flavour of fresh shareefa (custard apple).",
    price: 350,
    currency: "Rs",
    category: "Seasonal Flavors",
    image: "/images/shareefa.jpg",
    rating: 4.8,
    reviews: 1681,
    inStock: true,
    sizes: [{ label: "Cup", price: 350 }, { label: "Half Bucket", price: 800 }, { label: "Full Bucket", price: 1600 }, { label: "Family Bucket", price: 5200 }],
  },
  {
    slug: "chikoo",
    name: "Chikoo",
    tagline: "Sapota Sweetness",
    description: "Rich, caramel-sweet chikoo blended into smooth ice cream.",
    price: 400,
    currency: "Rs",
    category: "Seasonal Flavors",
    image: "/images/chikoo.jpg",
    rating: 4.8,
    reviews: 1718,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "orange",
    name: "Orange",
    tagline: "Zesty & Fresh",
    description: "Fresh oranges churned into a bright, citrusy cream.",
    price: 350,
    currency: "Rs",
    category: "Seasonal Flavors",
    image: "/images/orange.jpg",
    rating: 4.8,
    reviews: 1755,
    inStock: true,
    sizes: [{ label: "Cup", price: 350 }, { label: "Half Bucket", price: 800 }, { label: "Full Bucket", price: 1600 }, { label: "Family Bucket", price: 5200 }],
  },
  {
    slug: "cherry",
    name: "Cherry",
    tagline: "Bursting Cherries",
    description: "Sweet cherries folded into a soft, fruity base.",
    price: 350,
    currency: "Rs",
    category: "Seasonal Flavors",
    image: "/images/cherry.png",
    rating: 4.8,
    reviews: 1792,
    inStock: true,
    sizes: [{ label: "Cup", price: 350 }, { label: "Half Bucket", price: 800 }, { label: "Full Bucket", price: 1600 }, { label: "Family Bucket", price: 5200 }],
  },
  {
    slug: "strawberry",
    name: "Strawberry",
    tagline: "Farm-Fresh Berries",
    description: "Fresh farm strawberries in our signature cream base.",
    price: 400,
    currency: "Rs",
    category: "Seasonal Flavors",
    image: "/images/strawberry.webp",
    rating: 4.8,
    reviews: 1829,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "anwar-retol-mango",
    name: "Anwar Retol (Mango)",
    tagline: "Premium Anwar Retol",
    description: "Made with fresh Anwar Retol mangos - the premium king of mangoes.",
    price: 1000,
    currency: "Rs",
    category: "Seasonal Flavors",
    tag: "Bestseller",
    image: "/images/anwar-retol-mango.webp",
    rating: 4.8,
    reviews: 1866,
    inStock: true,
    sizes: [{ label: "Half Bucket", price: 1000 }, { label: "Full Bucket", price: 2000 }, { label: "Family Bucket", price: 6400 }],
  },
  {
    slug: "peach",
    name: "Peach",
    tagline: "Soft & Juicy",
    description: "Juicy peaches blended into a delicate, refreshing cream.",
    price: 400,
    currency: "Rs",
    category: "Seasonal Flavors",
    image: "/images/peach.webp",
    rating: 4.8,
    reviews: 1903,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "mango-special-bucket",
    name: "Mango Special Bucket",
    tagline: "Mango with Chunks",
    description: "Fresh mango ice cream loaded with mango chunks.",
    price: 1000,
    currency: "Rs",
    category: "Seasonal Flavors",
    tag: "Bestseller",
    image: "/images/mango-special-bucket.webp",
    rating: 4.8,
    reviews: 1940,
    inStock: true,
    sizes: [{ label: "Half Bucket", price: 1000 }, { label: "Full Bucket", price: 2000 }, { label: "Family Bucket", price: 6000 }],
  },
  {
    slug: "peshawari-surprise",
    name: "Peshawari Surprise",
    tagline: "3 Scoops of Delight",
    description: "3 Scoops (Peshawari, Kulfa & Pineapple), cocktail fruit, yellow & red jelly topped with mixed dry fruits, pineapple ring and cherry.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    image: "/images/peshawari-surprise.jpg",
    rating: 4.8,
    reviews: 1977,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "mango-special-bowl",
    name: "Mango Special Bowl",
    tagline: "Mango Lovers Dream",
    description: "2 scoops of mango with mango chunks and yellow jelly.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    image: "/images/mango-special-bowl.webp",
    rating: 4.8,
    reviews: 514,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "fruit-jelly",
    name: "Fruit Jelly",
    tagline: "Fruit & Rooh Afza",
    description: "2 scoops of Peshawari topped with mixed dry fruits, cocktail fruit, red jelly and Rooh Afza syrup.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    image: "/images/fruit-jelly.jpg",
    rating: 4.8,
    reviews: 551,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "kaju-rabri-falooda",
    name: "Kaju Rabri Falooda",
    tagline: "Cashew & Rabri",
    description: "2 scoops of Kaju and Rabri, fresh milk, noodles and yellow jelly topped with rabri, cashew, cocktail fruit and cherry.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    tag: "Specialty",
    image: "/images/kaju-rabri-falooda.webp",
    rating: 4.8,
    reviews: 588,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "kulfa-falooda",
    name: "Kulfa Falooda",
    tagline: "Kulfa Classic",
    description: "2 Kulfa scoops, fresh milk, noodles, mixed dry fruits topped with red jelly & cocktail fruit with cherry.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    tag: "Specialty",
    image: "/images/kulfa-falooda.jpg",
    rating: 4.8,
    reviews: 625,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "zafran-falooda",
    name: "Zafran Falooda",
    tagline: "Saffron Falooda",
    description: "2 Zafran scoops, fresh milk, noodles, dry fruits topped with yellow jelly & cocktail fruit with cherry.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    tag: "Specialty",
    image: "/images/zafran-falooda.webp",
    rating: 4.8,
    reviews: 662,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "special-falooda",
    name: "Special Falooda",
    tagline: "The Signature Falooda",
    description: "2 scoops (Pineapple & Rose), fresh milk, noodles and cocktail fruit topped with mixed dry fruits and red jelly.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    tag: "Specialty",
    image: "/images/special-falooda.webp",
    rating: 4.8,
    reviews: 699,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "simple-falooda",
    name: "Simple Falooda",
    tagline: "Simple & Classic",
    description: "1 Rose scoop, fresh milk and noodles topped with red jelly & gulab syrup.",
    price: 500,
    currency: "Rs",
    category: "Specialities",
    tag: "Specialty",
    image: "/images/simple-falooda.webp",
    rating: 4.8,
    reviews: 736,
    inStock: true,
    sizes: [{ label: "Regular", price: 500 }],
  },
  {
    slug: "kaju-rabri-piyala",
    name: "Kaju Rabri Piyala",
    tagline: "Piyala Special",
    description: "2 scoops Kaju Rabri, noodles, fresh rabri topped with pistachios and kaju.",
    price: 600,
    currency: "Rs",
    category: "Specialities",
    image: "/images/kaju-rabri-piyala.JPG",
    rating: 4.8,
    reviews: 773,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-peshawari",
    name: "Peshawari",
    tagline: "The 1948 Original Shake",
    description: "The very first flavour we ever made - dense, creamy and pure. A legacy of taste in every scoop.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-peshawari.webp",
    rating: 4.8,
    reviews: 810,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-pista",
    name: "Pista",
    tagline: "Roasted Iranian Pistachios Shake",
    description: "Heavily loaded with premium roasted pistachios for an earthy, nutty crunch.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-pista.jpg",
    rating: 4.8,
    reviews: 847,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-rose",
    name: "Rose",
    tagline: "Milkshake Shake",
    description: "A thick, creamy milkshake. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-rose.jpg",
    rating: 4.8,
    reviews: 884,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-strawberry-cheesecake",
    name: "Strawberry Cheesecake",
    tagline: "Strawberry & Cheesecake Shake",
    description: "Indulge with soft creamy texture ice cream with strawberry & cheesecake mixed in every bite of this most loved flavor.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-strawberry-cheesecake.webp",
    rating: 4.8,
    reviews: 921,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-strawberry",
    name: "Strawberry",
    tagline: "Farm-Fresh Berries Shake",
    description: "Fresh farm strawberries in our signature cream base.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-strawberry.webp",
    rating: 4.8,
    reviews: 958,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-pineapple",
    name: "Pineapple",
    tagline: "Tropical & Tangy Shake",
    description: "Sun-ripened pineapple blended into a smooth, refreshing cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-pineapple.jpg",
    rating: 4.8,
    reviews: 995,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-chocolate-chip",
    name: "Chocolate Chip",
    tagline: "Chocolate Chips in Cream Shake",
    description: "Silky cream studded with crunchy chocolate chips.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-chocolate-chip.webp",
    rating: 4.8,
    reviews: 1032,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-shareefa",
    name: "Shareefa",
    tagline: "Custard Apple Cream Shake",
    description: "The soft, honeyed flavour of fresh shareefa (custard apple).. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-shareefa.jpg",
    rating: 4.8,
    reviews: 1069,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-mango",
    name: "Mango",
    tagline: "Seasonal King of Fruits Shake",
    description: "Made with the finest seasonal mangoes, sweet and intensely fruity.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-mango.webp",
    rating: 4.8,
    reviews: 1106,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-lotus",
    name: "Lotus",
    tagline: "Milkshake Shake",
    description: "A thick, creamy milkshake. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-lotus.webp",
    rating: 4.8,
    reviews: 1143,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-injeer",
    name: "Injeer",
    tagline: "Fig Infusion Shake",
    description: "Sweet dried figs blended into a smooth, honeyed cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-injeer.webp",
    rating: 4.8,
    reviews: 1180,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-kulfa",
    name: "Kulfa",
    tagline: "Milkshake Shake",
    description: "A thick, creamy milkshake. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-kulfa.webp",
    rating: 4.8,
    reviews: 1217,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-orange",
    name: "Orange",
    tagline: "Zesty & Fresh Shake",
    description: "Fresh oranges churned into a bright, citrusy cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-orange.jpg",
    rating: 4.8,
    reviews: 1254,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-coffee",
    name: "Coffee",
    tagline: "Robust Coffee Shake",
    description: "Rich brewed coffee churned into a smooth, aromatic cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-coffee.jpg",
    rating: 4.8,
    reviews: 1291,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-cadbury",
    name: "Cadbury",
    tagline: "Classic Chocolate Shake",
    description: "Rich Cadbury chocolate folded into our signature cream base.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-cadbury.jpg",
    rating: 4.8,
    reviews: 1328,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-oreo-cookies",
    name: "Oreo Cookies",
    tagline: "Cookies & Cream Shake",
    description: "Crushed Oreo cookies swirled through rich cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-oreo-cookies.webp",
    rating: 4.8,
    reviews: 1365,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-chocolate-fudge",
    name: "Chocolate Fudge",
    tagline: "Milkshake Shake",
    description: "A thick, creamy milkshake. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-chocolate-fudge.jpg",
    rating: 4.8,
    reviews: 1402,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-blueberry",
    name: "Blueberry",
    tagline: "Berry Bliss Shake",
    description: "Plump blueberries folded into a soft, tart-sweet cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-blueberry.jpg",
    rating: 4.8,
    reviews: 1439,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-peach",
    name: "Peach",
    tagline: "Soft & Juicy Shake",
    description: "Juicy peaches blended into a delicate, refreshing cream.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-peach.webp",
    rating: 4.8,
    reviews: 1476,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-coconut-bounty",
    name: "Coconut Bounty",
    tagline: "Coconut Tropical Shake",
    description: "Indulge in the irresistible sweetness of Coconut Bounty, a tropical treat.. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-coconut-bounty.jpg",
    rating: 4.8,
    reviews: 1513,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-chikoo-shake",
    name: "Chikoo Shake",
    tagline: "Milkshake Shake",
    description: "A thick, creamy milkshake. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-chikoo-shake.jpg",
    rating: 4.8,
    reviews: 1550,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "shake-kaju-rabri-shake",
    name: "Kaju Rabri Shake",
    tagline: "Milkshake Shake",
    description: "A thick, creamy milkshake. Blended with fresh milk for a joyful experience in every sip.",
    price: 600,
    currency: "Rs",
    category: "Milkshakes",
    image: "/images/shake-kaju-rabri-shake.webp",
    rating: 4.8,
    reviews: 1587,
    inStock: true,
    sizes: [{ label: "Regular", price: 600 }],
  },
  {
    slug: "deal-01",
    name: "Deal 01",
    tagline: "Deals Classic",
    description: "A beloved deals crafted with the finest ingredients.",
    price: 2250,
    currency: "Rs",
    category: "Deals",
    image: "/images/deal-01.jpeg",
    rating: 4.8,
    reviews: 1624,
    inStock: true,
    sizes: [{ label: "Regular", price: 2250 }],
  },
  {
    slug: "deal-02",
    name: "Deal 02",
    tagline: "Deals Classic",
    description: "A beloved deals crafted with the finest ingredients.",
    price: 2400,
    currency: "Rs",
    category: "Deals",
    image: "/images/deal-02.jpeg",
    rating: 4.8,
    reviews: 1661,
    inStock: true,
    sizes: [{ label: "Regular", price: 2400 }],
  },
  {
    slug: "deal-03",
    name: "Deal 03",
    tagline: "Deals Classic",
    description: "A beloved deals crafted with the finest ingredients.",
    price: 5100,
    currency: "Rs",
    category: "Deals",
    image: "/images/deal-03.jpeg",
    rating: 4.8,
    reviews: 1698,
    inStock: true,
    sizes: [{ label: "Regular", price: 5100 }],
  },
  {
    slug: "deal-04",
    name: "Deal 04",
    tagline: "Deals Classic",
    description: "A beloved deals crafted with the finest ingredients.",
    price: 4800,
    currency: "Rs",
    category: "Deals",
    image: "/images/deal-04.jpeg",
    rating: 4.8,
    reviews: 1735,
    inStock: true,
    sizes: [{ label: "Regular", price: 4800 }],
  },
  {
    slug: "coffee",
    name: "Coffee",
    tagline: "Robust Coffee",
    description: "Rich brewed coffee churned into a smooth, aromatic cream.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/coffee.webp",
    rating: 4.8,
    reviews: 1772,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "kaju-rabri",
    name: "Kaju Rabri",
    tagline: "Cashew & Rabri",
    description: "Indulge in the rich and creamy delight of Kaju Rabri where the sweetness of cashews melds perfectly with the silky smoothness of condensed milk.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    tag: "Bestseller",
    image: "/images/kaju-rabri.JPG",
    rating: 4.8,
    reviews: 1809,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "blueberry",
    name: "Blueberry",
    tagline: "Berry Bliss",
    description: "Plump blueberries folded into a soft, tart-sweet cream.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/blueberry.webp",
    rating: 4.8,
    reviews: 1846,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "oreo-cookies",
    name: "Oreo Cookies",
    tagline: "Cookies & Cream",
    description: "Crushed Oreo cookies swirled through rich cream.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/oreo-cookies.webp",
    rating: 4.8,
    reviews: 1883,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "chocolate-fudge-brownie",
    name: "Chocolate Fudge Brownie",
    tagline: "Fudge Swirls",
    description: "Chocolate fudge blended with chunks of brownie.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    tag: "Bestseller",
    image: "/images/chocolate-fudge-brownie.webp",
    rating: 4.8,
    reviews: 1920,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "zafran-almond-roasted",
    name: "Zafran Almond Roasted",
    tagline: "Saffron Roasted Almond",
    description: "Premium saffron with roasted almonds.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/zafran-almond-roasted.jpg",
    rating: 4.8,
    reviews: 1957,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "lotus-biscoff",
    name: "Lotus Biscoff",
    tagline: "Biscoff Caramel",
    description: "Caramelised biscoff cookies in a silky caramel base.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/lotus-biscoff.webp",
    rating: 4.8,
    reviews: 1994,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "coconut-bounty",
    name: "Coconut Bounty",
    tagline: "Coconut Tropical",
    description: "Indulge in the irresistible sweetness of Coconut Bounty, a tropical treat.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/coconut-bounty.jpg",
    rating: 4.8,
    reviews: 531,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
  {
    slug: "chocolate-roasted-almond",
    name: "Chocolate Roasted Almond",
    tagline: "Premium Flavors Classic",
    description: "A beloved premium flavors crafted with the finest ingredients.",
    price: 400,
    currency: "Rs",
    category: "Premium Flavors",
    image: "/images/chocolate-roasted-almond.png",
    rating: 4.8,
    reviews: 568,
    inStock: true,
    sizes: [{ label: "Cup", price: 400 }, { label: "Half Bucket", price: 900 }, { label: "Full Bucket", price: 1800 }, { label: "Family Bucket", price: 5850 }],
  },
];

export const categories: Category[] = [
  "Regular Flavors",
  "Seasonal Flavors",
  "Premium Flavors",
  "Specialities",
  "Milkshakes",
  "Deals",
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function formatPrice(price: number, currency: "Rs" | "$"): string {
  if (currency === "$") {
    return `$${price.toFixed(2)}`;
  }
  return `Rs. ${price.toLocaleString("en-PK")}`;
}
